apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  # Easier to debug, so start with one instance
  instances: 1
  externalAccess:
    enabled: true
  # externalDatabase:false is NOT supported in production environments.
  externalDatabase:
    enabled: false
  # When the OpenShift cluster is dual-stack (IPv4 and IPv6)
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: JBOSS_HA_IP
          value: '0.0.0.0'
