apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-sso

commonLabels:
  lab: amq-sso


resources:
  - namespace.yaml
  - ../../../base/rhsso/
  - keycloak.yaml
  - activemq-realm.yaml
  - activemq-realm-client-broker.yaml
  - activemq-realm-client-console.yaml
  - activemq-realm-user-tinus.yaml
  - activemq-realm-console-user-admin.yaml


patches:
  - patch: |-
      - op: replace
        path: "/spec/targetNamespaces/0"
        value: "amq-sso"
    target:
      kind: OperatorGroup
      name: "rhsso-og"
