apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-broker

commonLabels:
  lab: amq-broker


resources:
  - namespace.yaml
  - ../../../base/amq-broker/
  - modules-security.yaml
  - amq-broker.yaml



patches:
  - patch: |-
      - op: replace
        path: "/spec/targetNamespaces/0"
        value: "amq-broker"
    target:
      kind: OperatorGroup
      name: "amq-broker-og"
